### ISSUE TITLE
[Enhancement] Full content

### ISSUE THREAD

**Issue by RebellionBritney** [ciderapp/Apple-Music-Electron#123]
Hi! 
I know this is an Apple Music issue (cause it's present in their web site) but when I click on my songs, or my playlists I need to scroll down the entire songs saved to play them all (especially on shuffle)
Is there a way you could fix it? That would be very cool. Thanks for you hard work.

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
