### ISSUE TITLE
[Enhancement] 'Add to quote' buttom

### ISSUE THREAD

**Issue by RebellionBritney** [ciderapp/Apple-Music-Electron#133]
Hi!
Something that's missing on Apple Music and the rest of the streaming platforms has, is the 'Add to quote' buttom. 
We have 'Play next' and the useless 'Play last'. If I want to add 3 songs in a specific order I need to use 'Play next' to add them in the quote and manually choose the order, when I used Tidal the first song I added with 'Play next' and the rest with 'Add to quote', even a whole album could be added it with that buttom.

Could you add it? I know it's not natively on Apple Music but it's so useful.

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
