### ISSUE TITLE
[BUG] Missing translations for custom settings buttons and settings menu.

### ISSUE THREAD

**Issue by cryptofyre** [ciderapp/Apple-Music-Electron#173]
![image](https://user-images.githubusercontent.com/33162551/129083964-fa2506c2-1341-45c7-8f6e-3ed4620e522a.png)
![image](https://user-images.githubusercontent.com/33162551/129083979-0cd9411d-4994-4d7b-a957-0522557c5b17.png)

**Comment by coredev-uk** [comment]
Translation of the settings menu itself is not possible with our current module. The context menu I may be able to do.

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
