### ISSUE TITLE
[Enhancement] Add Windows SMTC support and Exclusive audio modes using NodeRT

### ISSUE THREAD

**Issue by cryptofyre** [ciderapp/Apple-Music-Electron#174]
Documentation:
https://www.npmjs.com/package/@nodert-win10-20h1/windows.media
https://github.com/NodeRT/NodeRT

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
