### ISSUE TITLE
[Enhancement] Access to iCloud /local Library

### ISSUE THREAD

**Issue by egech01** [ciderapp/Apple-Music-Electron#220]
**Is your feature request related to a problem? Please describe.**
Would be nice if i can access my owned Music associated with my apple id without a Apple Music subscription.
Right now i have my songs synced through the icloud and this makes it available for all my (apple) devices. 
I use a Macbook, iPhone, iPad and a Windows PC. I can access my Music on all Apple Devices using the Music App except on my Windows PC where i have to use iTunes.
 iTunes seems to be not be further developed by Apple so i search for alternatives on Windows ...
This "Apple Music Electron App" for Windows seems to be the perfect fit. 

thanx 
Christian

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
