### ISSUE TITLE
[BUG] MEDIA_LICENSE error every 30 minutes

### ISSUE THREAD

**Issue by mysteriously** [ciderapp/Apple-Music-Electron#222]
Hi

**Describe the bug**
Every 30 minutes I receive MEDIA_LICENSE error which stops playback. After that, I can't play any music. Only restarting the app fixes it. It happenes on 2.50 stable and 2.50 alpha 1. I have tried to reset settings but it did not work. It happens for at least a week.

**To Reproduce**
1. Play any music for around 30 minutes
2. See the error

**Expected behavior**
Uninterrupted music playback or possibility to at least resume it.

**Screenshots**
![ML](https://user-images.githubusercontent.com/17072890/134155372-a8d8c2e1-783c-457d-9e68-3963f79dc495.png)
![ML2](https://user-images.githubusercontent.com/17072890/134155375-d9d34e68-2f01-4efc-99e3-51bf877d1556.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1 (build 19043)
 - Application Version 2.5.0 alpha 1

**Log File**
Check your log file for any errors or the last message to be sent and post them here.

**Additional context**

**Have you followed the troubleshooting guide found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting) and checked for any outstanding/pinned issues that can help?**
Yes
[main.log](https://github.com/Apple-Music-Electron/Apple-Music-Electron/files/7202409/main.log)

I dont know why log is so old. It happened again right before creating this thread.

**Comment by coredev-uk** [comment]
Yeah, I get this issue a lot too, its an issue with AM's site.

**Comment by cryptofyre** [comment]
Has this been happening to anyone else since this issue was made recently?

**Comment by child-duckling** [comment]
+1 for serpent#0815 in the Discord

**Comment by mysteriously** [comment]
2 days ago it was still happening. Music via iTunes works fine though.

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
