### ISSUE TITLE
[Enhancement] Playlist/Album Art Context Menu

### ISSUE THREAD

**Issue by coredev-uk** [ciderapp/Apple-Music-Electron#245]
Requested from the discord server by CrypticVader.

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
