### ISSUE TITLE
[Enhancement] Add 'Go to Current Song' option in the 3-dot menu to re-direct you back to the playlist the song was originally playing from.

### ISSUE THREAD

**Issue by pecanpiee** [ciderapp/Apple-Music-Electron#253]
**Is your feature request related to a problem? Please describe.**
When playing a song from a playlist (generally an Apple Music curated one), there is an option on the MacOS version of Apple Music (not Electron) to click on the 3-dots next to the song on the middle-top of the screen to 'Go to current song', which re-directs you back to the playlist the music it was playing from.

**Describe the solution you'd like**
Add an option in the 3-dot menu on the middle-top to re-direct you back to the playlist the song was originally playing from.

**Describe alternatives you've considered**
The only alternative is to not leave the screen of the playlist I was playing from, or just find it again manually.

**Additional context**

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
