### ISSUE TITLE
iTunes Remote via UR and the official Remote app from the App Store

### ISSUE THREAD

**Issue by SkyRexHUN** [ciderapp/Apple-Music-Electron#260]
**Is your feature request related to a problem? Please describe.**
I used to control my iTunes on Windows using two remote apps, however none of them finds Apple Music Electron.

**Describe the solution you'd like**
I want this remote function to be available in the Apple Mucic Electron app.

**Comment by cryptofyre** [comment]
We may not be able to get the **official** app working but we can definitely make a web app or something to fit your needs. Would that work?

**Comment by child-duckling** [comment]
This is being worked on.

iTunes + Remote communication is via the DACP (Apple's version of DAAP) protocol.

Sources we're using:
https://blacksmith-eng.com/doku/dacp#pairing_process
http://dacp.jsharkey.org/
http://daap.sourceforge.net/docs/

We basically need to create an Express.js server (on `_touch-able._tcp`) that bridges the gap between AME and the Remote client (on `_touch-remote._tcp`)

@vapormusic and I (@child-duckling) am working on it, on a branch off of @vapormusic 's fork

TODO
- [x] Detect remote
- [x] Pair remote (with the PIN)
- [ ] Respond to requests from remote

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
