### ISSUE TITLE
[BUG] Can only shuffle a certain amount of songs from library (Win11)

### ISSUE THREAD

**Issue by SkyRexHUN** [ciderapp/Apple-Music-Electron#273]
**Describe the bug**
When I play a song and turn on shuffle, I noticed that all the songs that play start with the letter 'A', because the app does not load more than like a few dozen songs at a time, meaning if I start to scroll down eventually more songs will load, but the app will unload the ones that are too far from where I am at the library. I have 5000 songs, so it is very apparent when I can only shuffle songs that start with the same letter to the one I'm playing at the moment.

**To Reproduce**
1. Go to any song
2. Click on play
3. Turn on shuffle
4. Check "Upcoming songs" menu

**Expected behavior**
A shuffled order of the whole library, not just some of it

**Screenshots**
![amshufflebug1](https://user-images.githubusercontent.com/92554890/138150819-84696a59-05f9-4082-b278-5d47df5f035c.png)
![amshufflebug2](https://user-images.githubusercontent.com/92554890/138150839-a480e8e1-af27-4e2b-9585-224bfe5a74cf.png)

**Environment Information**
 - OS *(e.g. Linux/Mac/Windows)*: Windows 11 Pro
 - Application Version *(e.g. 2.5.0)*: 2.5.0

**Log File**
Follow [this](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/FAQs#2-how-to-find-the-log-file) to find your log file.
[main.log](https://github.com/Apple-Music-Electron/Apple-Music-Electron/files/7383486/main.log)

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
