### ISSUE TITLE
[Enhancement] adult streamer mode

### ISSUE THREAD

**Issue by cryptofyre** [ciderapp/Apple-Music-Electron#276]
no questions asked. lets get this bread.

context:
![image](https://user-images.githubusercontent.com/33162551/138392082-885ca221-7b18-4977-a819-f86eeb415418.png)
![image](https://user-images.githubusercontent.com/33162551/138392074-eb8b3190-0ca1-4322-bce5-a3f1201c1e61.png)

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
