### ISSUE TITLE
[Enhancement] Sort Playlists by Recently Played or Recently Added

### ISSUE THREAD

**Issue by DoctorAnon** [ciderapp/Apple-Music-Electron#309]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
An Edit button similar to the one right of the "Library" tab on the left panel, but for the playlists tab - which once clicked would allow the user to sort their playlists either by Alphabetical order, Recently Played, Recently Added, and preferably by a custom user-defined order. 

**Describe alternatives you've considered**
There is currently no alternative to ordering playlists by means other than alphabetical.

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
