### ISSUE TITLE
[Enhancement] Pause/Mute audio when detecting a different audio feed

### ISSUE THREAD

**Issue by DoctorAnon** [ciderapp/Apple-Music-Electron#310]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A opt-in toggle in preferences > general settings which would automatically pause or mute any currently playing music in AME when it detects a different audio source, such as a youtube video or a discord call. 

**Describe alternatives you've considered**
Manually pausing/playing, not a big deal but its more convenient if it's done automatically.

**Additional context**
I mention opt-in toggle, off by default - because it could be annoying for individuals and sometimes there may be unintended audio sources that play for a brief second and stop the music - which is why I would prefer an opt-in toggle to give that option to those who want it.

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
