### ISSUE TITLE
[3.0.0 Finalization] Prepare for Microsoft Store release.

### ISSUE THREAD

**Issue by cryptofyre** [ciderapp/Apple-Music-Electron#330]
Finish setting up .appx packages and fixing shit to make it work with the app including modifying certain parts for copyright reasons.

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
