### ISSUE TITLE
[BUG] Window size go default when move the window in acrylic transparency effect.

### ISSUE THREAD

**Issue by Echo7251** [ciderapp/Apple-Music-Electron#337]
**Describe the bug**
Window size go default when move the window in acrylic transparency effect.

**To Reproduce**
1. Open AME and Set transparency effect to acrylic.
2. Relaunch.
3. Move the window then the window size will go default.
4. Whatever the window size is before, after move the window will change to the fixed size.
**Expected behavior**
When I move the window, the size don't change.

**Screenshots**

**Environment Information**
 - OS *(e.g. Linux/Mac/Windows)*: Windows 11 22000.282
 - Application Version *(e.g. 2.5.0)*:  2.5.0
 
**Additional context**

**Have you followed the troubleshooting guide and checked for any outstanding/pinned issues that can help?**
*Troubleshooting guide can be found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting).*
Yes
**Log File**
Follow [this](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/FAQs#2-how-to-find-the-log-file) to find your log file.
Attach your log file to the post but make sure to remove any LastFM keys that are in the file.

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
