### ISSUE TITLE
[Enhancement] Sort "Add to Playlist" list by Recently Added / Recently Played

### ISSUE THREAD

**Issue by DoctorAnon** [ciderapp/Apple-Music-Electron#345]
**Is your feature request related to a problem? Please describe.**
It is quite annoying to constantly have to scroll to the bottom of the list of "Add to playlist" playlists when adding a song, as the current order is dictated by Alphabetical order.

**Describe the solution you'd like**
An option either directly in the "Add to Playlist" pop-out, or a toggle in preferences which will sort the order of the "add to playlists" order.

**Describe alternatives you've considered**
The only work around is to simply scroll down to find your playlist in the alphabetical order, not a big issue if your chosen playlist to add songs to is alphabetically at the top or you have a small amount of playlists - but for those of us with large playlist amounts or with playlists ending in letters like XYZ, it is tedious and can get very irritating when adding many songs individually, having to scroll down every single.

Image below is how it is currently sorted, alphabetically.
![addto](https://user-images.githubusercontent.com/71120469/140637706-4ef0efab-f61e-4e23-9b92-51ff673620a6.png)

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
