### ISSUE TITLE
[Enhancement] Notify user if they are adding already-existing song to playlist.

### ISSUE THREAD

**Issue by DoctorAnon** [ciderapp/Apple-Music-Electron#346]
**Is your feature request related to a problem? Please describe.**
Currently on AME, if you add a song to a playlist that is already there, it does not prompt you - making it annoying as I will often add the same song several times, especially in large playlists where i cannot realistically remember every single song i added previously.

**Describe the solution you'd like**
When the user attempts to add a song to a playlist that is already existent in that playlist, pop-up a prompt which informs the user the song is already in the playlist, then give them the option to either skip adding the song or to add it anyways. The image below will provide useful context, it is the exact prompt the user receives on Android AM.
![androidampromt](https://user-images.githubusercontent.com/71120469/140637944-defdf18b-19d2-46a9-a2d3-a52a0111f694.png)

**Describe alternatives you've considered**
 The only other solution around this is to see a song i want to add, go to the playlist, check if it is there, and if it is not then go back and add it. This gets insanely tedious when adding many songs individually.

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
