### ISSUE TITLE
[Enhancement] Scroll bar in the Playlist

### ISSUE THREAD

**Issue by RedBlueKoi** [ciderapp/Apple-Music-Electron#348]
1. Request
There is no way to quickly scroll through the content in any place of the application and while it is not a problem in the big-sized content like in the "Listen Now", it is however a problem when you try to navigate through let's say Playlist.

2. Suggested solution
A few improvements can be done here to make navigation through the playlist easier. The easiest one will be to add a scroll bar 

3. Alternatives
As additional improvement would be nice to have a sort by recently added or any other kind of sorting.

**Comment by inalone** [comment]
There actually is a scroll bar, it's just disabled by default.

**Comment by booploops** [comment]
In 2.5.0 the option is called removeScrollbars under advanced in the settings window.
In the 3.0.0 beta this option is under Visual

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
