### ISSUE TITLE
[Enhancement] Zoom Out Button/

### ISSUE THREAD

**Issue by rhonXD** [ciderapp/Apple-Music-Electron#355]
This isn't much of a problem but a feature request, everything works fine flawlessly, however, my laptop screen is small. If only there is an option to lower the zoom level, then it'll be more fantastic. 

Thank you so much!

**Comment by vapormusic** [comment]
What is the version of the app are you using right now ? On 3.0.0 , Go to preferences ( by clicking the your avatar ), then scroll down to Interface Scaling Multiplier, you can decrease it to suit your view

**Comment by rhonXD** [comment]
I'm on 2.5.0, that the latest I can download. Sorry, I'm a newbie.

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
