### ISSUE TITLE
[BUG] Volume Slider overlaying over song bar

### ISSUE THREAD

**Issue by DoctorAnon** [ciderapp/Apple-Music-Electron#359]
**Describe the bug**

**To Reproduce**
1. Open AME 
2. Volume slider next to song title & desc at top is not overlayed.
3. Take bottom right corner of window, and slowly move in in the left-up direction
4. Volume slider will overlay into the song title/desc bar - potentially obscuring text.

**Expected behavior**
Volume bar would expectantly shrink with the window size or shift to the right to avoid being overlayed on the bar.

**Screenshots**
![unknown (2)](https://user-images.githubusercontent.com/71120469/141063405-2096a0c7-a59e-4cbb-8ce1-a26384277f26.png)

**Environment Information**
 - OS **Windows 11**
 - Application Version: **3.0.0**
 
**Additional context**
Shrinking even further circumnavigates the problem as it just removes the volume slider, but this is not an ideal solution

**Have you followed the troubleshooting guide and checked for any outstanding/pinned issues that can help?**
Yes

**Log File**
[main.log](https://github.com/Apple-Music-Electron/Apple-Music-Electron/files/7510437/main.log)

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
