### ISSUE TITLE
[Enhancement] WebSocket API and Web Remote

### ISSUE THREAD

**Issue by booploops** [ciderapp/Apple-Music-Electron#364]
WebSocket API
WebSocket API documentation
Web Remote

If these take too long save for a future patch after 3.0.0 releases.

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
