### ISSUE TITLE
[Enhancement] Show currently playing track bitrate

### ISSUE THREAD

**Issue by mysteriously** [ciderapp/Apple-Music-Electron#365]
**Is your feature request related to a problem? Please describe.**
Even if we select Extreme audio quality (990kbps), I highly doubt all tracks are 990kbps.

**Describe the solution you'd like**
Display currently playing track bitrate in right top corner of the 'now-playing-container'.

**Describe alternatives you've considered**
Calculate bitrate based on the size and length of the track.

**Additional context**
I can not imagine listening to music without knowing its quality

**Comment by DoctorAnon** [comment]
Pretty sure this is impossible as Apple dosent give that info and they can't check it via files since its all streamed.

**Comment by mysteriously** [comment]
You are suggesting that the app is not aware how much data it requests, processes and so on

**Comment by mysteriously** [comment]
This is how Amazon Music displays audio quality
![image](https://user-images.githubusercontent.com/17072890/143725256-e582e15c-74d7-4782-9502-f75bd33f7ed9.png)

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
