### ISSUE TITLE
Custom Music Playlists Do Not Play Properly

### ISSUE THREAD

**Issue by gabehxd** [ciderapp/Apple-Music-Electron#375]
**Describe the bug**

**To Reproduce**
1. create playlist with uploaded music
2.  shuffle playlist

**Expected behavior**
Trying to shuffle a playlist with music uploaded by the user causes the app to skip songs.
**Screenshots**
https://user-images.githubusercontent.com/22406854/142339984-f5635f54-2466-49be-8605-ef907f0cff43.mp4

**Environment Information**
 - Windows 11
 - Apple Music v2.5.0

**Have you followed the troubleshooting guide and checked for any outstanding/pinned issues that can help?**
*Troubleshooting guide can be found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting).*
Yes

**Log File**
[main.log](https://github.com/Apple-Music-Electron/Apple-Music-Electron/files/7559306/main.log)

**Comment by micah-mcgonigal** [comment]
I'm experiencing this as well, but unfortunately the issue is on Apple's end. The same exact thing happens on the browser version.

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
