### ISSUE TITLE
[Enhancement] Install location on Install

### ISSUE THREAD

**Issue by coredev-uk** [ciderapp/Apple-Music-Electron#377]
Requested by @Hiltonium on the Discord server.
Various other installation options such as Analytics should also be added.

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
