### ISSUE TITLE
[Enhancement] Pipeline to send Song info for Github Readme

### ISSUE THREAD

**Issue by Adil-MohammedK** [ciderapp/Apple-Music-Electron#379]
**Is your feature request related to a problem? Please describe.**
No. 

**Describe the solution you'd like**
Spotify has API which can be used to get current playing info. This is then used by Vercel instance to show it in Github readme. Look at my Readme page for example. So we send the current music to a personal Vercel or Firebase instance to show it as animated page in ReadMe

**Describe alternatives you've considered**
Also there are other alternatives.
[using github actions ](https://dev.to/gargakshit/how-i-added-my-spotify-statistics-to-my-github-readme-4jdd)
[Another Guthub solution](https://github.com/janaSunrise/spotify-playing-readme)
[Using Heroku](https://github.com/isladot/spotify-readme-widget)
Or we could create our own API ID generated by AME which is passed to AME website server and then to Github

**Additional context**
![image](https://camo.githubusercontent.com/16f2a395ae805134def0759bdab70ac99a04442fb163d57b07602769118bfaa4/68747470733a2f2f6e6f7661746f72656d2e6164696c2d6d6f68616d6d65646b2e76657263656c2e6170702f6170692f73706f74696679)

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
