### ISSUE TITLE
[BUG] iTunes Inspired theme makes account button unclickable

### ISSUE THREAD

**Issue by vladaad** [ciderapp/Apple-Music-Electron#383]
**Describe the bug**
The account/preferences button is not clickable when the iTunes inspired (MacOS Style) theme is selected while Application Frame is disabled.

**To Reproduce**
1. Open the app with default settings
2. Go to preferences
3. Select the iTunes Inspired (MacOS Style) theme
4. Attempt to click the account button

**Expected behavior**
The account button is clickable (or the theme forces the application frame to be MacOS-style)

**Screenshots**
[Video](https://user-images.githubusercontent.com/59199127/142777931-1187f53f-acdd-425d-8810-ece6da2a10f0.mp4)

**Environment Information**
 - Windows 10 Pro 21H1
 - Apple Music Electron 3.0.0
 
**Additional context**
Might be an oversight with the MacOS-inspired theme not also enabling the correct application frame.

**Have you followed the troubleshooting guide and checked for any outstanding/pinned issues that can help?**
*Troubleshooting guide can be found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting).*
Yes

**Log File**
[main.log](https://github.com/Apple-Music-Electron/Apple-Music-Electron/files/7577051/main.log)

**Comment by N0chteil** [comment]
https://github.com/Apple-Music-Electron/Apple-Music-Electron-Themes/blob/5e84153c72ce200cd7361b68ea6b2b493793c286/itunes_macos.css#L201

`width: calc(100% - 90px);` must be changed to `calc(100% - var(--windowsChromeWidth));`

**Comment by vapormusic** [comment]
> https://github.com/Apple-Music-Electron/Apple-Music-Electron-Themes/blob/5e84153c72ce200cd7361b68ea6b2b493793c286/itunes_macos.css#L201
> 
> `width: calc(100% - 90px);` must be changed to `width: calc(100% - var(--windowsChromeWidth));`

Please make a PR of this

**Comment by N0chteil** [comment]
> 


> > https://github.com/Apple-Music-Electron/Apple-Music-Electron-Themes/blob/5e84153c72ce200cd7361b68ea6b2b493793c286/itunes_macos.css#L201
> > `width: calc(100% - 90px);` must be changed to `width: calc(100% - var(--windowsChromeWidth));`
> 
> Please make a PR of this

https://github.com/Apple-Music-Electron/Apple-Music-Electron-Themes/pull/11
