### ISSUE TITLE
[BUG] Cannot build the application. Yarn times out. 

### ISSUE THREAD

**Issue by colourfuloctopus** [ciderapp/Apple-Music-Electron#385]
**Describe the bug**
Followed the instructions to build the application. It times out during yarn install. Possible it's not a bug on your end but I've been attempting this for a while now and it continues to fail at the same point. 

**To Reproduce**
Follow the build instructions. 

**Expected behavior**
Application builds.

**Environment Information**
Void Linux. 
 
**Additional context**
Yarn times out at https://github.com/vapormusic/node-upnp-device-client, but I can access the link in a browser. [Complete output.](https://pastebin.com/X4k2BRR6) 

**Have you followed the troubleshooting guide and checked for any outstanding/pinned issues that can help?**
*Troubleshooting guide can be found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting).*
Yes

Unrelated to the bug report but a Flatpak version would be wonderful. Unlike Snap it does not require systemd and as such is accessible on all Linux distrutions whereas Snap does not run on those without it.

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
