### ISSUE TITLE
Please compile more recent version to Snap.

### ISSUE THREAD

**Issue by dirkmittler** [ciderapp/Apple-Music-Electron#391]
On snapcraft.io, the version is 2.4.0, and on many platforms, including my Debian 9 / Stretch machine, the snap cannot be run, due to a known permissions error. This makes the software look bad, and unavailable to some users.

Versions of this application that work have already been compiled to AppImages etc., which work fine on the same platform. Wouldn't it be a good idea, just to build an up-to-date snap (and then, to upload that)?

For example, v3.0.0 of the AppImage runs without issues on my machine.

Dirk

**Comment by coredev-uk** [comment]
I believe this can only be done by @cryptofyre

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
