### ISSUE TITLE
[BUG] When going to add/create new playlist, if any option overlaps the song info box/control area, the option to to add to playlist disappears

### ISSUE THREAD

**Issue by kickinitlegit** [ciderapp/Apple-Music-Electron#398]
**Describe the bug**

**To Reproduce**
1. Click on triple dots next to song
2. Hover over "Add to Playlist" option
3. If submenu opens up on top of song info/control bar, then playlist options disappear. Most likely the result of the Application registering user input elsewhere.

**Expected behavior**
Keep Add to Playlist option box live

![image](https://user-images.githubusercontent.com/22462289/143797602-452d56d6-8bbe-4bfe-9a26-6155825a3acf.png)

![image](https://user-images.githubusercontent.com/22462289/143797627-c4a5e3ee-2feb-4c24-8939-a64115858d23.png)

**Environment Information**
 - Windows 10
 - Application Version 3.0.0

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
