### ISSUE TITLE
3.0 installs in win10: Will not start (processes start then crash)

### ISSUE THREAD

**Issue by docace911** [ciderapp/Apple-Music-Electron#409]
Where should the crash log be located? I checked %appdata%\applemusic but don't see it

Basically
1. Uninstalled 2.5
2. deleted Applemusic folder form appdata
3. Install 3.0
4. Went fine see icon on desktop
5. Launch 
6. See a quick flash (like program starting) then nothing
7. If i watch task manager i see 3-4 applemusic.exe pop up then go away

Tried to also run as ADMIN

Windows 10, latest patches

**Comment by Aebian** [comment]
happens to me on Windows 11 too

**Comment by cmd9919** [comment]
Translation from the original text: Me too, windows 11 enterprise 22000.376, can not open after installation, crash。

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
