### ISSUE TITLE
AME 3.0.0 MacOS Build Missing?

### ISSUE THREAD

**Issue by mdredz** [ciderapp/Apple-Music-Electron#411]
Is the 3.0.0 build for MacOS missing or did i miss a memo somewhere about it being intentionally missing?

**Comment by vapormusic** [comment]
It is missing because the MacOS app need to be digitally signed by Apple, and currently we're unable to do so.

**Comment by mdredz** [comment]
Awww shucks. That's a shame really. Thanks for the clarification!

**Comment by lucadenhez** [comment]
Yeah I hope a MacOS build comes out soon!

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
