### ISSUE TITLE
Option to Disable Preventing Sleep

### ISSUE THREAD

**Issue by jonathanmwood** [ciderapp/Apple-Music-Electron#414]
Small idea for an enhancement. Frequently when I'm using Apple Music Electron, I'll pause a track and leave my PC for a while. My PC is set to sleep automatically after a while however after pausing a track with Apple Music Electron, automatic sleeping is disabled meaning I'll come back hours later to my PC still running.

Running:
`powercfg -requests `

in Command Prompt shows this:

```
[DRIVER] USB Audio Device (USB\VID_08BB&PID_2902&MI_00\7&d7d2448&0&0000)
An audio stream is currently in use.
[DRIVER] Legacy Kernel Caller
```

It would be amazing if this behaviour could be toggled with a switch in the settings.

PS, appologies if this is something I have to configure outside of the program. Not sure about that. 

PPS, I don't know how to add the "Enhancement" label to this post so, sorry about that.

**Comment by LordManhattan** [comment]
Hmm, I'm not having this issue. I always have the app open in its own smaller window, and my system goes to sleep when it should, so it looks like it might be a bug on your side, maybe driver issue(?)

Running Windows 11 (22000.376)

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
