### ISSUE TITLE
[Enhancement] Playlist cover editing capability.

### ISSUE THREAD

**Issue by certifiedgeek** [ciderapp/Apple-Music-Electron#416]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to switch to iTunes or my other devices just to add or change the cover art for a playlist.

**Describe the solution you'd like**
I would like to be able to edit playlist covers from within the AME app.

**Describe alternatives you've considered**
iTunes, Apple Music on Android and iOS. All of these support cover editing.

**Additional context**
Just that.

**Comment by cryptofyre** [comment]
This feature *could* be implemented into Cider. AME is currently in the process of sunsetting/finishing and any feature requests will be forwarded.

**Comment by certifiedgeek** [comment]
what's cider....?

**Comment by CrypticVader** [comment]
AME is evolving into Cider, which does not depend on Apple music web.
[Cider Repo](https://github.com/ciderapp/cider)

**Comment by child-duckling** [comment]
#417

**Comment by certifiedgeek** [comment]
alright i'll be waiting then.
the project looks promising.
