### ISSUE TITLE
Autoscroll Interpret 

### ISSUE THREAD

**Issue by Itsredsect** [ciderapp/Apple-Music-Electron#420]
If the artist or title is too long, I wish it would move from right to left so you can read everything well.

**Comment by Itsredsect** [comment]
https://media.discordapp.net/attachments/875051684781490246/922567725178568754/unknown.png

**Comment by child-duckling** [comment]
Wrong repository.

Try making an issue in the [ciderapp/Cider](https://github.com/ciderapp/Cider) repository.
