### ISSUE TITLE
[BUG] Problem with the Interpret Button 

### ISSUE THREAD

**Issue by Itsredsect** [ciderapp/Apple-Music-Electron#421]
Maybe a Bug: If you want to press the name of the performer with the mouse, you have to aim slightly over the font so that it is selected. This is a little confusing. Example: I am listening to Rammstein and want to go to the artist. So I go to the top where I see the title and the artist and press on that. But now it is so that I have to go slightly upwards so that I can click on this.

**Comment by child-duckling** [comment]
Wrong repository.

Try making an issue in the [ciderapp/Cider](https://github.com/ciderapp/Cider) repository.
