### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Itsredsect** [ciderapp/Apple-Music-Electron#423]
for example, if I want to play the song Bad Girls in my Shazam playlist, I have to go to the song Eternal Youth so I can play Bad Girls. This is quite confusing. Also, there is the problem when I have random mode on and want to listen to a specific song, I usually go to the song and click on it. But now it plays me a completely different song. My understanding of the mode is that when I skip the song I get a random song, but when I click on a specific one I also want it to play. 

![grafik](https://user-images.githubusercontent.com/95378207/147290363-50391946-ebcd-4c21-9540-bbf781d9c233.png)

**Comment by child-duckling** [comment]
Wrong repository.

Try making an issue in the [ciderapp/Cider](https://github.com/ciderapp/Cider) repository.
