### ISSUE TITLE
[BUG] Can't close, extend or minimize

### ISSUE THREAD

**Issue by bgpvp** [ciderapp/Apple-Music-Electron#425]
**Describe the bug**
Cannot click on the close extend or minimizing buttons.

**To Reproduce**
1. Try closing, extending or minimizing the app by clicking the app

**Expected behavior**
Should close, extend or minimize the app

**Environment Information**
 - OS *(e.g. Linux/Mac/Windows)*:  Windows
 - Application Version *(e.g. 2.5.0)*: 3.0.0

**Have you followed the troubleshooting guide and checked for any outstanding/pinned issues that can help?**
*Troubleshooting guide can be found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting).*
Yes/No

Yes

**Log File**
Follow [this](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/FAQs#2-how-to-find-the-log-file) to find your log file.
Attach your [log file](https://www.hastebin.com/enezeputax) to the post but make sure to remove any LastFM keys that are in the file.

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
