### ISSUE TITLE
Apple-Music-Electron hijacked my iTunes !

### ISSUE THREAD

**Issue by Perplexer1** [ciderapp/Apple-Music-Electron#426]
**Describe the bug**
Since I ran Apple-Music-Setup-2.5.0.exe, the application auto-installed into a predetermined location and ever since then, I cannot use my regular iTunes. The "For You", "Browse" and "Radio" sections in iTunes no longer load any content! I have uninstalled Apple-Music-Setup, I have reinstalled iTunes, I have rebooted the PC, I have even attempted to use system restore (although that seems to have failed) and I just can't get those three sections back in my iTunes! WHAT THE HELL !?!?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment Information**
 - OS * Windows 7 64-bit Ultimate
 - Application Version *(e.g. 2.5.0)*: 
 
**Additional context**

**Have you followed the troubleshooting guide and checked for any outstanding/pinned issues that can help?**
*Troubleshooting guide can be found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting).*
Yes/No

**Log File**
Follow [this](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/FAQs#2-how-to-find-the-log-file) to find your log file.
Attach your log file to the post but make sure to remove any LastFM keys that are in the file.

**Comment by child-duckling** [comment]
Wat? We embed the music.apple.com site. This might be a network issue on your end.
