### ISSUE TITLE
[BUG] Last.fm scrobble stops working after first songs finishes playing

### ISSUE THREAD

**Issue by ElLucioVpe** [ciderapp/Apple-Music-Electron#429]
**Describe the bug**
When you play songs it only scrobbles the first one, after that it stops working.

**To Reproduce**
1. Activate Last.fm scrobble
2. Play from playlist, album, library, etc
3. It will scrobble the first track
4. The next ones won't be scrobbled

**Environment Information**
 - Windows
 - Application Version *(e.g. 2.5.0)*: 3.0.0
 
**Additional context**
Discord Rich Presence doesn't seem to update as well, it could be related to this

**Have you followed the troubleshooting guide and checked for any outstanding/pinned issues that can help?**
*Troubleshooting guide can be found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting).*
Yes

**Log File**
Follow [this](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/FAQs#2-how-to-find-the-log-file) to find your log file.
Attach your log file to the post but make sure to remove any LastFM keys that are in the file
[main.log](https://github.com/ciderapp/Apple-Music-Electron/files/7811873/main.log)
.

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
