### ISSUE TITLE
[Enhancement] Fixed band/graphic equalizer

### ISSUE THREAD

**Issue by Nosh118** [ciderapp/Apple-Music-Electron#93]
A 10 band fixed/graphic equalizer like the one shown below would be awesome.
![image](https://user-images.githubusercontent.com/67752804/122688193-bf8f0e80-d212-11eb-9d52-fdf4a287eb55.png)

**Comment by child-duckling** [comment]
Awaiting for third party.

Closing until response.

**Comment by cryptofyre** [comment]
https://chrome.google.com/webstore/detail/sound-equalizer/jgbgcmhkbphbhbfeeighjmiaoonppcpl

putting this here in the event we ever wanna bundle an extension.

**Comment by mysteriously** [comment]
You have Equalizer APO which works system wide as long as you are not using wasapi exclusive (which is currently unavailable in electron anyway)

**Comment by quacksire** [comment]
This app will be sunseted very soon and we are NOT maintaining this app
unless of a security issue. We encourage you to try Cider, our new music app built from scratch. Issues filled on that repository will be seen and will be acted upon. Please join our discord and see the #nightly-builds channel for a current build.

[Cider can be found here](https://github.com/ciderapp/Cider)
